### ISSUE TITLE
Unexpected use of spaces and tabs

### ISSUE THREAD

**Issue by xotan135** [burtonc/HaveTheyBeenPwned#2]
When i try to run the code right after git clone it gives me the unexpected use of indents and space. 

I have went to the raw page and copied and pasted it into an IDE editor and saved it and tried to run it as well with the same results.

The issue states it starts at line 67

**Comment by burtonc** [comment]
I've updated the shebang to point to python2.7 on the local host, if this doesn't work you need to manually run it python2.7 HaveTheyBeenPwned.py

Tested on the latest build of Kali

**Comment by xotan135** [comment]
Thanks for the update
